version: "3.8"
services:
  app:
    image: node:12-alpine
    command: sh -c "echo helloworld"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USE: root
      MYSQL_PASSWORD: secret
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mysql-data:

networks:
  default:
    external:
      name: nasa-net